In [33]:
import numpy as np
import pandas as pd 
import os


In [34]:

risk = pd.read_csv("C:\\Users\\NEHA\\Desktop\\archive\\demography_copd_risk.csv")
risk.head()

Age  gender    BMI  Risk
0   70       0  28.47     1
1   73       0  21.00     1
2   75       0  33.70     1
3   84       0  33.53     1
4   75       1  25.21     1

In [35]:
X = risk[['Age','gender','BMI']]
y = risk['Risk']


In [36]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 42)



# RF

In [37]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=100, random_state=42)

In [38]:
rf.fit(x_train, y_train)

RandomForestClassifier(random_state=42)

In [39]:
y_pred = rf.predict(x_test)

# Evaluating the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.9230769230769231


In [40]:
report = classification_report(y_test, y_pred)
print('Classification Report:')
print(report)

Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.89      1.00      0.94         8
           2       1.00      1.00      1.00         4

    accuracy                           0.92        13
   macro avg       0.63      0.67      0.65        13
weighted avg       0.85      0.92      0.89        13



C:\Users\NEHA\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\NEHA\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\NEHA\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [41]:
cm = confusion_matrix(y_test, y_pred)
print('Confusion Matrix:')
print(cm)

Confusion Matrix:
[[0 1 0]
 [0 8 0]
 [0 0 4]]


# SVM

In [42]:
from sklearn.svm import SVC
s = SVC(kernel='rbf', C=1, gamma='auto')

In [43]:
s.fit(x_train, y_train)

SVC(C=1, gamma='auto')

In [53]:
y1_pred = s.predict(x_test)

# Evaluating the accuracy of the model
accuracy = accuracy_score(y_test, y1_pred)

print("Accuracy:", accuracy)

Accuracy: 0.6153846153846154


In [56]:
report = classification_report(y_test, y1_pred)
print('Classification Report:')
print(report)

Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.62      1.00      0.76         8
           2       0.00      0.00      0.00         4

    accuracy                           0.62        13
   macro avg       0.21      0.33      0.25        13
weighted avg       0.38      0.62      0.47        13



C:\Users\NEHA\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\NEHA\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\NEHA\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [55]:
cm = confusion_matrix(y_test, y1_pred)
print('Confusion Matrix:')
print(cm)

Confusion Matrix:
[[0 1 0]
 [0 8 0]
 [0 4 0]]


# LOGR

In [47]:
from sklearn.linear_model import LogisticRegression

In [48]:
clf = LogisticRegression(random_state=0, multi_class='multinomial', max_iter=1000)


In [49]:
clf.fit(x_train, y_train)

C:\Users\NEHA\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(max_iter=1000, multi_class='multinomial', random_state=0)

In [50]:
y2_pred = clf.predict(x_test)

# Evaluating the accuracy of the model
accuracy = accuracy_score(y_test, y2_pred)

print("Accuracy:", accuracy)

Accuracy: 0.7692307692307693


In [51]:
report = classification_report(y_test, y2_pred)
print('Classification Report:')
print(report)

Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.78      0.88      0.82         8
           2       1.00      0.75      0.86         4

    accuracy                           0.77        13
   macro avg       0.59      0.54      0.56        13
weighted avg       0.79      0.77      0.77        13



In [52]:
cm = confusion_matrix(y_test, y2_pred)
print('Confusion Matrix:')
print(cm)

Confusion Matrix:
[[0 1 0]
 [1 7 0]
 [0 1 3]]
